more debug text

diff --git a/bin/install b/bin/install
--- a/bin/install
+++ b/bin/install
@@ -27,26 +27,26 @@ install_postgis() {
 
     local configure_options="$(construct_configure_options)"
 
-    echo "Building with options: $configure_options"
+    echo -e "Building with options: $configure_options"
 
-    echo "\nConfigure 1:\n"
-    ARCHFLAGS="-arch i386 -arch x86_64" ./configure $configure_options || (echo "\n\nFAIL 1"; exit 1)
+    echo -e "\nConfigure 1:\n"
+    ARCHFLAGS="-arch i386 -arch x86_64" ./configure $configure_options || (echo -e "\n\nFAIL 1"; exit 1)
 
-    echo "\nMake 2:\n"
-    ARCHFLAGS="-arch i386 -arch x86_64" make || (echo "\n\nFAIL 2"; exit 1)
+    echo -e "\nMake 2:\n"
+    ARCHFLAGS="-arch i386 -arch x86_64" make || (echo -e "\n\nFAIL 2"; exit 1)
 
-    echo "\nMake Install 3:\n"
-    ARCHFLAGS="-arch i386 -arch x86_64" make install || (echo "\n\nFAIL 3"; exit 1)
+    echo -e "\nMake Install 3:\n"
+    ARCHFLAGS="-arch i386 -arch x86_64" make install || (echo -e "\n\nFAIL 3"; exit 1)
     cd contrib || exit 1
 
-    echo "\nMake 4:\n"
-    ARCHFLAGS="-arch i386 -arch x86_64" make || (echo "\n\nFAIL 4"; exit 1)
+    echo -e "\nMake 4:\n"
+    ARCHFLAGS="-arch i386 -arch x86_64" make || (echo -e "\n\nFAIL 4"; exit 1)
 
-    echo "\nMake Install 5:\n"
-    ARCHFLAGS="-arch i386 -arch x86_64" make install || (echo "\n\nFAIL 5"; exit 1)
+    echo -e "\nMake Install 5:\n"
+    ARCHFLAGS="-arch i386 -arch x86_64" make install || (echo -e "\n\nFAIL 5"; exit 1)
 
     mkdir $install_path/data || exit 1
-    $install_path/bin/initdb -D $install_path/data || (echo "\n\nFAIL 6"; exit 1)
+    $install_path/bin/initdb -D $install_path/data || (echo -e "\n\nFAIL 6"; exit 1)
   )
 }
 
